### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [elix-x/Colourful-Blocks#1]
Crash Log
https://gist.github.com/DPxKnightxZero/2eff524ffb8337cc3ab6

Client Log
https://gist.github.com/DPxKnightxZero/e516b3d237c357dc5600

**Comment by Elix-x** [comment]
Fixed in 1.1.1.

**Comment by P3rf3ctXZer0** [comment]
<3 you are the best <3

**Comment by Elix-x** [comment]
Thanks.
Also, before launching mc, delete extensions folder in config/colorfulblocks :) .
