### ISSUE TITLE
[1.9] Server crash at startup

### ISSUE THREAD

**Issue by kwpugh** [elix-x/Colourful-Blocks#12]
Crash report: http://pastebin.com/raw/EC6C0ur7

Forge 1887
Mod: ColorfulBlocks-1.3-1.9.jar
Excore-1.5.3-1.9.jar

**Comment by Elix-x** [comment]
You're on dedicated server, right?
Crash fix is coming!

**Comment by kwpugh** [comment]
Correct.

**Comment by Elix-x** [comment]
Ok. Working on it.
