### ISSUE TITLE
Again Crash :(

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [elix-x/Colourful-Blocks#3]
Crash Log - Latest Release ["[Universal]-ColorfullBlocks-1.1.2-1.7.10"] and ["[Universal]-Excore-1.2.2-1.7.10"]
https://gist.github.com/DPxKnightxZero/809c10855cc5050f7750

Full Client Log - Latest Release ["[Universal]-ColorfullBlocks-1.1.2-1.7.10"] and ["[Universal]-Excore-1.2.2-1.7.10"] 
https://gist.github.com/DPxKnightxZero/7d8863ccf39c7b4b1a4f

**Comment by Elix-x** [comment]
That's another issue that previous ones.
