### ISSUE TITLE
Crash startup

### ISSUE THREAD

**Issue by f0kx** [elix-x/Colourful-Blocks#4]
http://paste.ee/p/ntuPb

**Comment by Elix-x** [comment]
What? That's impossible! There's nothing on line 546 that can throw null pointers...

Can you post log please?

**Comment by f0kx** [comment]
What log do you mean??

**Comment by Elix-x** [comment]
In your mc folder, there's logs folder. Inside there must be ?-lates.log. ? is client on client and server on server. Also, check that you have latest version of both KBO and Excore and try again. If it does not work, post both crash report and log.

**Comment by f0kx** [comment]
do you mean this file "fml-client-latest"?

EDIT: BTW its Singleplayer only!client on client

**Comment by Elix-x** [comment]
Yes.
And CoBl is server compatible.

**Comment by Elix-x** [comment]
Is it first time you launch CoBl?
What OS do you have?
And finally, i think i have a solution, but it is on your end:
-Open extensions folder in config/colorfulblocks:
--Open each folder inside extensions folder and:
---If there's file called "lang" without extension, delete it.
---If there's no folder called "lang", create one.

Also, i think i know how to fix this for further erros like this... Update should be tomorow.
