### ISSUE TITLE
Crash again ... Can I ever use this mod?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [elix-x/Colourful-Blocks#6]
Server Full Log -> https://gist.github.com/DPxKnightxZero/a52448a9770e643d42c5

Server Crash Log -> https://gist.github.com/DPxKnightxZero/54308b8be51a07323b90

**Comment by Elix-x** [comment]
For some reasons, invalid names for tool ingredients were generated. Can you send me your materials.json in generated extension?

**Comment by P3rf3ctXZer0** [comment]
Yes; absolutely! I will send you my entire workspace if it means this awesome concecpt mod can work   : D !

I am happy to test all your creations but for testing purposes I am going use your latest mods.

**Comment by Elix-x** [comment]
No need for entire workspace, just materials.json in generated extension.

**Comment by P3rf3ctXZer0** [comment]
https://www.dropbox.com/s/qv9ju8jcd1wz2qy/DebuggerPack-Logs-Configs-Asm-Pack-%7B1%7D.zip?dl=1

**Comment by P3rf3ctXZer0** [comment]
Well as desperate as I am I basically gave you all files I can give you that may help with debugging.

**Comment by Elix-x** [comment]
Are you sure you gave correct ones?
Because i don't see any files in generated extension.

Anyways, i think i may know where the problem may be coming from, but still not 100% sure.

**Comment by P3rf3ctXZer0** [comment]
Yes

**Comment by P3rf3ctXZer0** [comment]
I have given you all the files I freshly launched Minecraft with the mod present.

**Comment by Elix-x** [comment]
And... it crashes? With these files?
Ok, it seems that there's something really wrong with item finder.

**Comment by P3rf3ctXZer0** [comment]
Yeah that was my thoughts exactly.

**Comment by Elix-x** [comment]
I think i may have fixed it, but you'll have to wait a bit, as there are some important changes in next update.

**Comment by P3rf3ctXZer0** [comment]
Understood thank you :)

**Comment by Elix-x** [comment]
Excore update will come tomorrow, CoBl update may come few days after.

**Comment by P3rf3ctXZer0** [comment]
thank you very much for your effort; I look forward to finally showing off your mod : D

You will be able to see it in action here -> http://www.technicpack.net/modpack/pz-ultima-1710-testing.795173

**Comment by Elix-x** [comment]
Awesome!
I'll feature your modpack on my mod hub. Are you ok with it?

**Comment by P3rf3ctXZer0** [comment]
Absolutely : D

**Comment by Elix-x** [comment]
Then i'll put when update comes!

**Comment by P3rf3ctXZer0** [comment]
Um... I needed 1.7.10

**Comment by Elix-x** [comment]
Excore 1.3.3 is for 1.7.10, 1.8, 1.8.8 and 1.8.9. Read changelog closely.
Also, it is not working with current CoBl version anyways :) .
