### ISSUE TITLE
The song that never ends! - Yay for startup crashes.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [elix-x/Colourful-Blocks#9]
Startup Crash 

Partial Crash -> https://gist.github.com/DPxKnightxZero/c250cc1518ccc68c7750

Full Crash log -> https://gist.github.com/DPxKnightxZero/114c9b5ef14a1a866fa3

I believe it is caused by Metallurgy mod so I hope that helps.

Evidence in belief -> https://gist.github.com/DPxKnightxZero/407b1ac36618f10425d3

**Comment by Elix-x** [comment]
First of all, please delete Colorful Blocks config folder, update to 1.2.1 and reproduce this crash.
Meanwhile, i'm going to check what happened.

**Comment by P3rf3ctXZer0** [comment]
Will do!

Partial Crash log -> https://gist.github.com/DPxKnightxZero/760864a272b3d29b5956

Full Crash log -> https://gist.github.com/DPxKnightxZero/f575b92816ef68606838

Crash still seems to be between Colourful Blocks and Metallugry 
https://gist.github.com/DPxKnightxZero/280b8d521a1c23a618c8

If I may ... it has been a long time since Metallurgy had an update maybe work on a custom branch specifically for this mod?
